apiVersion: v2
name: hyperf
version: v1.0.0
appVersion: latest
description: ğŸ”‹ (PHP / Hyperf) ç”Ÿäº§å°±ç»ªçš„Dockeré•œåƒï¼Œå¸¦æœ‰è‡ªåŠ¨Hyperfå®‰è£…ç¨‹åº
icon: https://images.budiuyun.net/i/2025/06/09/6846f62f3a3f6.png
maintainers:
  - name: niehaoran
    email: 179866495@qq.com
annotations:
  budiu/app-category-zh: å¼€å‘å·¥å…·
