replicaCount: 1
workloadType: Deployment
image:
  imageRegistry: docker.1ms.run
  repository: coldpig/lskypro-docker
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    webport: 80
networkLimits:
  enabled: true
  egress: 2M
  ingress: 1M
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi
persistence:
  enabled: true
  path: /var/www/html
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: local
env:
  env1:
    name: DB_CONNECTION
    value: mysql
    description: MySQL数据库连接类型
    title: 数据库连接方式
  env2:
    name: DB_HOST
    value: 127.0.0.1
    description: MySQL数据库服务器主机名
    title: 数据库主机地址
  env3:
    name: DB_PORT
    value: '3306'
    description: MySQL数据库连接端口
    title: 数据库端口
  env4:
    name: DB_DATABASE
    value: lskypro
    description: LskyPro使用的数据库名
    title: 数据库名称
  env5:
    name: DB_USERNAME
    value: root
    description: 连接数据库的用户名
    title: 数据库用户名
  env6:
    name: DB_PASSWORD
    value: MyPassword
    description: 连接数据库的密码
    title: 数据库密码
